/**
 * A script's production direction describes how the clip is performed and
 * filmed. Product, performer, and location appearance live in their own
 * records and reference images; repeating them here creates competing visual
 * authorities downstream.
 */
export const PRODUCTION_DIRECTION_SECTIONS = [
  "PERFORMANCE",
  "PHYSICS",
  "CAMERA CHARACTER",
  "STYLE",
  "AUDIO",
  "OUTPUT SETTINGS",
] as const;

export type ProductionDirectionSection =
  (typeof PRODUCTION_DIRECTION_SECTIONS)[number];

export interface ProductionDirectionDraft {
  performance: string;
  physics: string;
  cameraCharacter: string;
  style: string;
  audio: string;
  outputSettings: string;
}

/** Turns the structured authoring result into the editable text stored with a
 * script. New scripts can therefore only create owned sections, while saved
 * scripts remain plain text that an operator may revise. */
export function formatProductionDirection(
  direction: ProductionDirectionDraft,
): string {
  return [
    `PERFORMANCE: ${direction.performance}`,
    `PHYSICS: ${direction.physics}`,
    `CAMERA CHARACTER: ${direction.cameraCharacter}`,
    `STYLE: ${direction.style}`,
    `AUDIO: ${direction.audio}`,
    `OUTPUT SETTINGS: ${direction.outputSettings}`,
  ].join("\n");
}

export const FRAME_DIRECTION_SECTIONS = [
  "PERFORMANCE",
  "PHYSICS",
  "CAMERA CHARACTER",
  "STYLE",
] as const satisfies readonly ProductionDirectionSection[];

export const VIDEO_DIRECTION_SECTIONS = [
  "PERFORMANCE",
  "PHYSICS",
  "CAMERA CHARACTER",
  "AUDIO",
  "OUTPUT SETTINGS",
] as const satisfies readonly ProductionDirectionSection[];

/** Headings generated by older script versions. They remain boundaries so a
 * safe section can never absorb a following legacy appearance section. */
const LEGACY_APPEARANCE_SECTIONS = [
  "OVERVIEW",
  "TALENT",
  "PRODUCT",
  "LOCATION",
  "LIGHTING",
  "FRAMING",
  "VOICE",
  "REALISM",
  "POSITIVE LOCKS",
  "NEGATIVE CONSTRAINTS",
] as const;

const KNOWN_SECTIONS = [
  ...PRODUCTION_DIRECTION_SECTIONS,
  ...LEGACY_APPEARANCE_SECTIONS,
] as const;

function withoutMarkdownHeading(line: string): string {
  return line
    .trim()
    .replace(/^#{1,6}\s*/, "")
    .replaceAll("**", "")
    .trim();
}

function sectionAtStart(line: string): {
  section: (typeof KNOWN_SECTIONS)[number];
  firstLine: string;
} | null {
  const normalized = withoutMarkdownHeading(line);
  const upper = normalized.toUpperCase();
  const section = KNOWN_SECTIONS.find(
    (candidate) => upper === candidate || upper.startsWith(`${candidate}:`),
  );
  if (!section) return null;

  return {
    section,
    firstLine:
      upper === section ? "" : normalized.slice(section.length + 1).trim(),
  };
}

function looksLikeUnknownHeading(line: string): boolean {
  const normalized = withoutMarkdownHeading(line);
  return (
    /^[A-Z][A-Z0-9 &/_-]{1,40}:/.test(normalized) ||
    /^[A-Z][A-Z0-9 &/_-]{1,40}$/.test(normalized)
  );
}

/**
 * Selects only the direction sections a downstream generation stage owns.
 *
 * Unknown headings are dropped conservatively. This is intentional: an old
 * or manually edited block that cannot be classified may contain stale
 * wardrobe, product, or location text, while the structured beat list still
 * carries every required action and camera instruction.
 */
export function selectProductionDirection(
  productionPrompt: string | null | undefined,
  allowedSections: readonly ProductionDirectionSection[],
): string {
  const parsed = new Map<string, string[]>();
  let current: string | null = null;

  for (const rawLine of (productionPrompt ?? "").split("\n")) {
    const heading = sectionAtStart(rawLine);
    if (heading) {
      current = heading.section;
      parsed.set(heading.section, heading.firstLine ? [heading.firstLine] : []);
      continue;
    }
    if (looksLikeUnknownHeading(rawLine)) {
      current = null;
      continue;
    }
    if (current) parsed.get(current)?.push(rawLine.trim());
  }

  return allowedSections
    .flatMap((section) => {
      const body = parsed.get(section)?.filter(Boolean).join("\n");
      return body ? [`${section}: ${body}`] : [];
    })
    .join("\n");
}
